import Groq from 'groq-sdk';
import { DetectionResult, ParagraphAnalysis, ClassificationLabel } from './detection/types';

const apiKey = process.env.GROQ_API_KEY || '';

const groq = new Groq({
    apiKey: apiKey,
});

/**
 * Split text into paragraphs for analysis
 */
function splitIntoParagraphs(text: string): string[] {
    return text
        .split(/\n\n+/)
        .map((p) => p.trim())
        .filter((p) => p.length > 0);
}

const DISCLAIMER =
    'Results are generated by Groq AI and may not be 100% accurate. Use as a helper tool.';

export async function analyzeWithAI(text: string, language?: string): Promise<DetectionResult> {
    try {
        if (!process.env.GROQ_API_KEY) {
            throw new Error("GROQ_API_KEY is missing");
        }

        const paragraphs = splitIntoParagraphs(text);

        // If no paragraphs, handle as single block
        if (paragraphs.length === 0 && text.trim()) {
            paragraphs.push(text.trim());
        } else if (paragraphs.length === 0) {
            return {
                overall: { human: 0, aiGenerated: 0, aiRefined: 0 },
                paragraphs: [],
                disclaimer: DISCLAIMER
            };
        }

        let detectedLang = language || "Unknown";

        // Analyze paragraphs in parallel
        const analyses = await Promise.all(
            paragraphs.map(async (para, index) => {
                try {
                    const completion = await groq.chat.completions.create({
                        messages: [
                            {
                                role: 'system',
                                content: `You are an expert AI content detector. Analyze the text for AI-generated patterns.
                                
                                Instructions:
                                1. Detect the language of the text.
                                2. If a specific language is requested (${language || "Auto"}), use that language's linguistic patterns.
                                3. Provide a NUANCED score between 0 and 100. **DO NOT default to 0 or 100.**
                                4. Return ONLY JSON. Format: { "score": number, "label": "AI" | "Human", "reason": "short explanation in detected language", "detectedLanguage": "Name" }`
                            },
                            {
                                role: 'user',
                                content: para
                            }
                        ],
                        model: 'llama-3.3-70b-versatile',
                        temperature: 0.1,
                        response_format: { type: 'json_object' }
                    });

                    const content = completion.choices[0]?.message?.content;
                    if (!content) throw new Error('No content returned from Groq');

                    const result = JSON.parse(content);

                    if (index === 0 && result.detectedLanguage) {
                        detectedLang = result.detectedLanguage;
                    }

                    // Map Groq result to our types (No ai_refined)
                    const score = result.score || 0;
                    let label: ClassificationLabel = score > 50 ? 'ai_generated' : 'human';

                    let confidence = label === 'human' ? 100 - score : score;

                    return {
                        index,
                        label,
                        confidence,
                        text: para,
                        reason: result.reason || "Analiz edildi."
                    } as ParagraphAnalysis;

                } catch (err) {
                    console.error(`Groq hatası [Para ${index}]:`, err);
                    return {
                        index,
                        label: 'human',
                        confidence: 0,
                        text: para,
                        reason: "AI servisine ulaşılamadı."
                    } as ParagraphAnalysis;
                }
            })
        );

        // ... hata kontrolü ...

        const labelCounts = {
            human: 0,
            ai_generated: 0,
            ai_refined: 0
        };

        analyses.forEach(a => {
            if (a.label === 'human') labelCounts.human++;
            else if (a.label === 'ai_refined') labelCounts.ai_refined++;
            else labelCounts.ai_generated++;
        });

        const total = analyses.length;
        const overall = {
            human: Math.round((labelCounts.human / total) * 100),
            aiGenerated: Math.round((labelCounts.ai_generated / total) * 100),
            aiRefined: Math.round((labelCounts.ai_refined / total) * 100)
        };

        // Fix rounding errors
        const sum = overall.human + overall.aiGenerated + overall.aiRefined;
        if (sum !== 100 && total > 0) {
            overall.human += (100 - sum);
        }

        return {
            overall,
            paragraphs: analyses,
            disclaimer: DISCLAIMER,
            detectedLanguage: detectedLang
        };

    } catch (error) {
        console.error('Groq Ana Hatası:', error);
        throw error;
    }
}

export async function humanizeWithAI(text: string): Promise<string> {
    try {
        const completion = await groq.chat.completions.create({
            messages: [
                {
                    role: 'system',
                    content: `You are a professional editor. Rewrite the following text to make it sound more natural, human-like, and less repetitive. 
                    Vary sentence structure and vocabulary. Keep the original meaning and tone. 
                    IMPORTANT: Detect the language of the input text and rewrite it in the SAME language.
                    Do NOT add any introductory text like "Here is the rewritten version:". Just return the rewritten text.`
                },
                {
                    role: 'user',
                    content: text
                }
            ],
            model: 'llama-3.3-70b-versatile',
            temperature: 0.7,
        });

        return completion.choices[0]?.message?.content || text;
    } catch (error) {
        console.error('Groq Humanize Error:', error);
        throw new Error('Failed to humanize text');
    }
}
