import Groq from 'groq-sdk';
import { DetectionResult, ParagraphAnalysis, ClassificationLabel } from './detection/types';

const apiKey = process.env.GROQ_API_KEY || '';
console.log("API Key Check:", apiKey ? `Present (Starts with ${apiKey.substring(0, 5)}...)` : "MISSING");

const groq = new Groq({
    apiKey: apiKey,
});

/**
 * Split text into paragraphs for analysis
 */
function splitIntoParagraphs(text: string): string[] {
    return text
        .split(/\n\n+/)
        .map((p) => p.trim())
        .filter((p) => p.length > 0);
}

const DISCLAIMER =
    'Results are generated by Groq AI and may not be 100% accurate. Use as a helper tool.';

export async function analyzeWithAI(text: string): Promise<DetectionResult> {
    console.log("Groq analizi başladı... Metin uzunluğu:", text.length);

    try {
        if (!process.env.GROQ_API_KEY) {
            throw new Error("GROQ_API_KEY is missing");
        }

        const paragraphs = splitIntoParagraphs(text);

        // If no paragraphs, handle as single block
        if (paragraphs.length === 0 && text.trim()) {
            paragraphs.push(text.trim());
        } else if (paragraphs.length === 0) {
            return {
                overall: { human: 0, aiGenerated: 0, aiRefined: 0 },
                paragraphs: [],
                disclaimer: DISCLAIMER
            };
        }

        // Analyze paragraphs in parallel
        const analyses = await Promise.all(
            paragraphs.map(async (para, index) => {
                try {
                    const completion = await groq.chat.completions.create({
                        messages: [
                            {
                                role: 'system',
                                content: `Sen bir AI tespit uzmanısın. Gönderilen metni analiz et. Cevabını SADECE JSON formatında ver: { "score": 0-100 arası sayı (AI olma ihtimali), "label": "AI" | "Human" | "Mixed", "reason": "kısa açıklama (maksat 1 cümle)" }.`
                            },
                            {
                                role: 'user',
                                content: para
                            }
                        ],
                        model: 'llama-3.3-70b-versatile', // Updated to latest supported model
                        temperature: 0.1,
                        response_format: { type: 'json_object' }
                    });

                    const content = completion.choices[0]?.message?.content;
                    if (!content) throw new Error('No content returned from Groq');

                    console.log(`Groq [Para ${index}] cevabı:`, content);

                    const result = JSON.parse(content);

                    // Map Groq result to our types
                    let label: ClassificationLabel = 'human';
                    const score = result.score || 0;

                    // Basit eşik değerleri
                    if (result.label === 'AI' || score > 80) label = 'ai_generated';
                    else if (result.label === 'Mixed' || (score > 40 && score <= 80)) label = 'ai_refined';
                    else label = 'human';

                    // Confidence hesapla (skora göre)
                    let confidence = label === 'human' ? (100 - score) : score;
                    if (confidence < 0) confidence = 0;

                    return {
                        index,
                        label,
                        confidence,
                        text: para,
                        reason: result.reason || "Analiz edildi."
                    } as ParagraphAnalysis;

                } catch (err) {
                    console.error(`Groq hatası [Para ${index}]:`, err);
                    return {
                        index,
                        label: 'human', // Mecburen bir label
                        confidence: 0,
                        text: para,
                        reason: "Sistem hatası: AI servisine ulaşılamadı. Lütfen tekrar deneyin."
                    } as ParagraphAnalysis;
                }
            })
        );

        // Eğer hepsi hata aldıysa, ana hatayı fırlat
        const allFailed = analyses.every(a => (a.reason || "").includes("ulaşılamadı"));
        if (allFailed) {
            throw new Error("AI servisine ulaşılamadı");
        }

        // Calculate overall scores
        const labelCounts = {
            human: 0,
            ai_generated: 0,
            ai_refined: 0,
        };

        analyses.forEach(a => {
            if (a.label === 'human') labelCounts.human++;
            else if (a.label === 'ai_generated') labelCounts.ai_generated++;
            else labelCounts.ai_refined++;
        });

        const total = analyses.length;
        const overall = {
            human: Math.round((labelCounts.human / total) * 100),
            aiGenerated: Math.round((labelCounts.ai_generated / total) * 100),
            aiRefined: Math.round((labelCounts.ai_refined / total) * 100),
        };

        // Fix rounding errors
        const sum = overall.human + overall.aiGenerated + overall.aiRefined;
        if (sum !== 100 && total > 0) {
            if (overall.aiGenerated >= overall.human) overall.aiGenerated += (100 - sum);
            else overall.human += (100 - sum);
        }

        return {
            overall,
            paragraphs: analyses,
            disclaimer: DISCLAIMER
        };

    } catch (error) {
        console.error('Groq Ana Hatası:', error);
        throw error;
    }
}

export async function humanizeWithAI(text: string): Promise<string> {
    try {
        const completion = await groq.chat.completions.create({
            messages: [
                {
                    role: 'system',
                    content: `You are a professional editor. Rewrite the following text to make it sound more natural, human-like, and less repetitive. 
                    Vary sentence structure and vocabulary. Keep the original meaning and tone. 
                    Do NOT add any introductory text like "Here is the rewritten version:". Just return the rewritten text.`
                },
                {
                    role: 'user',
                    content: text
                }
            ],
            model: 'llama-3.3-70b-versatile', // Updated to latest supported model
            temperature: 0.7,
        });

        return completion.choices[0]?.message?.content || text;
    } catch (error) {
        console.error('Groq Humanize Error:', error);
        throw new Error('Failed to humanize text');
    }
}
